version: '2'
services:
  drupal-web:
    hostname: drupal-web
    build:
      context: .
      dockerfile: ./docker/apache-php/Dockerfile
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:80"
    depends_on:
      - drupal-mysql
    links:
      - drupal-mysql:mysql
    environment:
      DOCKER_IMAGE: "apache-php"
      APP_FILES_REGION: "{{AWS_FILES_REGION}}"
      VCAP_SERVICES: >-
        {
          "docker-mysql": [{
            "name": "mysql",
            "tags": ["mysql"],
            "credentials": {
              "host": "mysql",
              "port": 3306,
              "username": "drupal",
              "password": "drupal",
              "db_name": "drupal"
            }
          }],
          "docker-s3": [{
            "name": "s3",
            "tags": ["s3"],
            "credentials": {
              "access_key_id": "{{AWS_ACCESS_KEY_ID}}",
              "secret_access_key": "{{AWS_SECRET_ACCESS_KEY}}",
              "bucket": "{{AWS_FILES_BUCKET}}"
            }
          }]
        }
      DRUPAL_THEME: "bootstrap_18f"
      DRUPAL_DB: "bootstrap"
      DRUPAL_SALT: "true"
      DRUPAL_INIT: "false"
      DRUPAL_SYNC: "true"
    volumes:
      - .:/var/www
  drupal-mysql:
    hostname: drupal-mysql
    image: mysql:latest
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - drupal-data:/var/lib/mysql
volumes:
  drupal-data:
    external: false
