<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\kanban_entity\Entity\KanbanProfile;

/**
 * Implements hook_theme().
 */
function kanban_entity_theme() {
  return array(
    'kanban_board' => array(
      'variables' => array('states' => array(), 'wips' => array()),
    ),
    'kanban_board_item' => array(
      'variables' => array('node' => NULL),
    ),
  );
}

/**
 * Menu argument loader. Returns a Kanban profile entity
 *
 * @param $id
 * @return \Drupal\Core\Entity\EntityInterface|static
 */
function kanban_profile_load($id) {
  return \KanbanProfile::load($id);
}