kanban_entity.kanban_profile.*:
  type: config_entity
  label: 'Kanban profile'
  mapping:
    id:
      type: string
      label: 'Kanban profile identifier'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Name'
    weight:
      type: integer
      label: 'Weight'
    workflow:
      type: string
      label: 'Workflow'
