palette:
  top: '#B3EFFF'
  bottom: '#00CFFF'
  bg: '#ffffff'
  sidebar: '#ffffff'
  sidebarborders: '#1C304A'
  footer: '#000000'
  titleslogan: '#1C304A'
  text: '#1C304A'
  link: '#046B99'
logo: 'public://color/bartik-d78e89cb/logo.svg'
stylesheets:
  - 'public://color/bartik-d78e89cb/colors.css'
files:
  - 'public://color/bartik-d78e89cb/logo.svg'
  - 'public://color/bartik-d78e89cb/colors.css'
