palette:
  top: '#000000'
  bottom: '#000000'
  bg: '#ffffff'
  sidebar: '#ffffff'
  sidebarborders: '#1C304A'
  footer: '#1C304A'
  titleslogan: '#B3EFFF'
  text: '#1C304A'
  link: '#046B99'
logo: 'public://color/bartik-9b64204d/logo.svg'
stylesheets:
  - 'public://color/bartik-9b64204d/colors.css'
files:
  - 'public://color/bartik-9b64204d/logo.svg'
  - 'public://color/bartik-9b64204d/colors.css'
