definitions:
  contact__site_page:
    weight: -49
    menu_name: footer
    parent: ''
    expanded: false
    enabled: true
  user__page:
    menu_name: account
    parent: ''
    weight: -48
    expanded: false
    enabled: true
  user__logout:
    menu_name: account
    parent: ''
    weight: -47
    expanded: false
    enabled: true
  node__add_page:
    enabled: false
    menu_name: tools
    parent: ''
    expanded: false
    weight: 0
  tracker__page:
    enabled: false
    menu_name: tools
    parent: ''
    weight: 0
    expanded: false
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
