module:
  action: 0
  automated_cron: 0
  backup_migrate: 0
  basic_auth: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bootstrap_layouts: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  default_content: 0
  deploy: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  entity_storage_migrate: 0
  facets: 0
  field: 0
  field_group: 0
  field_group_migrate: 0
  field_ui: 0
  file: 0
  filter: 0
  flysystem: 0
  flysystem_s3: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  key_value: 0
  kint: 0
  layout_plugin: 0
  link: 0
  menu_link_config: 0
  menu_ui: 0
  multiversion: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panelizer: 0
  panels: 0
  panels_ipe: 0
  path: 0
  quickedit: 0
  rdf: 0
  relaxed: 0
  replication: 0
  rest: 0
  restui: 0
  rules: 0
  search_api: 0
  search_api_db: 0
  serialization: 0
  shortcut: 0
  simple_oauth: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  toolbar: 0
  tour: 0
  tracker: 0
  update: 0
  user: 0
  views_ui: 0
  workspace: 0
  menu_link_content: 1
  views: 10
  minimal: 1000
theme:
  stable: 0
  classy: 0
  bootstrap: 0
  bootstrap_18f: 0
  seven: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
