type:
  'field:field_full_name': 0
  'field:user_picture': 0
  'field:field_team': 0
  'field:field_supervisor': 0
  'field:field_bio': 0
  'field:field_mobile_phone_number': 0
  'field:field_fec_phone_extension': 0
  'field:field_office_number': 0
  'field:field_work_hours': 0
  'field:field_flex_cws_schedule': 0
  'field:field_parent': 0
  'field:body': 0
  'field:field_fec_email': 0
  'field:field_manager': 0
  'field:field_membership': 0
  'field:field_projects': 0
  'field:field_linked_projects': 0
  'field:field_linked_dependencies': 0
  'field:field_linked_workflows': 0
  'field:field_linked_applications': 0
  'field:field_linked_services': 0
  'field:field_linked_infrastructure': 0
  'field:field_members': 0
  'field:field_vendor_type': 0
  'field:field_link': 0
  'field:field_fec_poc': 0
  'field:field_business_poc': 0
  'field:field_system': 0
  'field:field_strategic_align_commission': 0
  'field:field_strategic_align_it': 0
  'field:field_budget': 0
  'field:field_budget_justification': 0
  'field:field_architecture': 0
  'field:field_links': 0
  'field:field_critical_patch_period': 0
  'field:field_integrated_with_ad': 0
  'field:field_it_poc': 0
  'field:field_type': 0
  'field:field_access_information': 0
  'field:field_maintenance_schedule': 0
  'field:field_sla': 0
  'field:field_infrastructure_type': 0
  'field:field_requirement_type': 0
  'field:field_files': 0
  'field:field_diagrams': 0
  'field:field_poc_name': 0
  'field:field_poc_email': 0
  'field:field_poc_phone': 0
  'field:field_policy_type': 0
  'field:field_project_status': 0
  'field:field_teams': 0
  'field:field_linked_requirements': 0
  'field:field_linked_policy': 0
  'field:field_environment_type': 0
  'field:field_team_status': 0
