api_root: /relaxed
resources:
  'relaxed:db':
    HEAD:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
    GET:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
    POST:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
    PUT:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
    DELETE:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
  'relaxed:attachment':
    HEAD:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
    GET:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
    PUT:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
    DELETE:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
  'relaxed:bulk_docs':
    POST:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
  'relaxed:changes':
    GET:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
  'relaxed:doc':
    HEAD:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
    GET:
      supported_formats:
        - json
        - mixed
      supported_auth:
        - cookie
        - basic_auth
    PUT:
      supported_formats:
        - json
        - related
      supported_auth:
        - cookie
        - basic_auth
    DELETE:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
  'relaxed:revs_diff':
    POST:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
  'relaxed:local:doc':
    HEAD:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
    GET:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
    PUT:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
  'relaxed:root':
    GET:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
  'relaxed:session':
    GET:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
  'relaxed:ensure_full_commit':
    POST:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
  'relaxed:all_dbs':
    GET:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
  'relaxed:all_docs':
    GET:
      supported_formats:
        - json
      supported_auth:
        - cookie
        - basic_auth
_core:
  default_config_hash: r77vqoPGHQWXV0qlQmMfkUsvGDsQcWPmcDnC1K4C3i8
username: admin
password: YWRtaW45ODc=
