resources:
  'entity:node':
    GET:
      supported_formats:
        - csv
        - hal_json
        - json
        - xml
      supported_auth:
        - token_bearer
    POST:
      supported_formats:
        - hal_json
      supported_auth:
        - token_bearer
    DELETE:
      supported_formats:
        - hal_json
      supported_auth:
        - token_bearer
    PATCH:
      supported_formats:
        - hal_json
      supported_auth:
        - token_bearer
  'relaxed:db':
    HEAD:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    POST:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    PUT:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    DELETE:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  'relaxed:attachment':
    HEAD:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    PUT:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    DELETE:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  'relaxed:bulk_docs':
    POST:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  'relaxed:changes':
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  'relaxed:doc':
    HEAD:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    PUT:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    DELETE:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  'relaxed:revs_diff':
    POST:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  'relaxed:local:doc':
    HEAD:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    PUT:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  'relaxed:root':
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  'relaxed:session':
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  'relaxed:ensure_full_commit':
    POST:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  'relaxed:all_dbs':
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  'relaxed:all_docs':
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
link_domain: null
_core:
  default_config_hash: E9VXRiWZNet4YVBv8j9WQmTlgb-rOjo0MiCSdgV0Guw
