third_party_settings:
  shortcut:
    module_link: true
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: assets/logo.png
favicon:
  use_default: false
  path: assets/favicon.ico
  mimetype: image/vnd.microsoft.icon
