favicon:
  mimetype: image/vnd.microsoft.icon
  path: assets/favicon.ico
  url: ''
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: assets/logo.png
  url: ''
  use_default: false
_core:
  default_config_hash: 9rAU4Pku7eMBQxauQqAgjzlcicFZ2As6zEa6zvTlCB8
